= How To Git
{localdatetime}
:toc:
:toc-title: Inhaltsverzeichnis
:toclevels: 2
:sectnums:
:icons: font
//:source-highlighter: highlightjs
:source-highlighter: rouge
:xrefstyle: full
:figure-caption: Abbildung
:table-caption: Tabelle
:experimental:

== Voraussetzungen

=== Visual Studio Code
- GitLens Erweiterung installieren
- Source Control ist bereits enthalten

=== GitHub Desktop
- link:https://desktop.github.com/[GitHub Desktop Download]

=== .gitconfig includieren
Jeder muss nach dem Clonen von der Repo die `.gitconfig` local includieren. (Gilt nur für diese Repo)

Dafür muss dieses Kommando einmal zu Beginn im Ordner der Repo ausgeführt werden.
```shell
git config --local include.path ../.gitconfig
```

== Konventionen

=== Dokumentation:

====== Branches
* `main` enthält eine abgesegnete Dokumentation.
* `iterarion-_n_` enthalten die Änderungen der entsprechenden Iteration.


Paar Tage vor einem Iteration-Ende wird ein Pull Request erstellt, wo ein Review stattfindet. Probleme während der Iteration können in den entsprechenden Issues kommentiert werden.

// * 	Hier können die Änderungen reviewed werden, Hinweise gegeben werden etc.
// ** 	Wie und warum?
// * 	_Rebase and merge_ erfolgt durch Julian/Jonas/Carl/? durch:
// ** 	git checkout development
// **  git rebase master


=== Entwicklung:
*_Relevant, sobald Code geschrieben wird_*

Es werden Feature-Branches eingeführt. Jedes Issue wird auf einem dedizierten Branch (mit deskriptivem Namen) bearbeitet.

_Genauere Informationen_:

*   https://guides.github.com/introduction/flow/
*   https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

Der Pull-Request unterliegt dann einem Review.


== Workflow

Wir befinden uns im Repository _Dokumentation_.

=== Issue erstellen + KANBAN Board
*	Erstellen eines Issues
**	Beschreibender Titel  (z.B. Kategorie: Aufgabe), Labels etc.
** 	Checkboxen zur Beschreibung hinzufügen falls es sich anbietet (guter Überblick über Fortschritt)
**	Bearbeiter festlegen wenn bereits bekannt
**  *Hinzufügen zum KANBAN Board* und zum aktuellen Meilenstein

*	Card des erstellten Issues im Board platzieren (To-Do, In progress etc.)


=== Issue bearbeiten
* Lokal mit VSCode auf dem entsprechenden Iteration-Branch `iterartion-_n_` das Issue bearbeiten

[WARNING]
====
Vor dem `git push` einen `git pull` ausführen, um lokale Dateien auf den neuesten Stand zu bringen.

* *VSCode*: Sync Icon neben dem Branchauswahlmenü klicken
* *GitHub Desktop*: letzten Tab zum synchronisieren klicken
====

=== Git Pull (Rebase)

> Wie kann ich meine lokalen Änderungen auf den neuesten Stand von Branch `iteration-_n_` bringen?

==== Was ist ein Rebase?
Mit einem Rebase werden bestehende Änderungen nicht zusammengemischt wie beim Merge, was einen extra Commit (Merge-Commit) erzeugt, sondern die Commits an einen neuen Ursprung verschoben. Dabei wird sozusagen die "Geschichte neu geschrieben".

Einen Rebase darf man nur machen, wenn man sich sicher ist, dass keiner mehr an der aktuellen Branch arbeitet, da es zu unangenehmen Synchronisierungsproblemen kommt.

* Erklärung: https://www.atlassian.com/de/git/tutorials/rewriting-history/git-rebase

*Was ist der Vorteil?*

> Ein sauberer, geradliniger Commit-Verlauf.

==== Anleitung GUI

===== GitHub Dektop

. (Aktuellen `iteration-_n_`-Branch auswählen)
. Menü `Branch` -> `Rebase Current Branch` (kbd:[Ctrl + Shift + E])
. 	Auswahl von `*origin*/iteration-_n_` -> `Start Rebase`
.. 	Wenn Konflikte: `Open in Visual Studio Code`
.. 	VSCode öffnet sich und Konflikte können behoben werden (farbliche Darstellung)
.. 	In der Datei befinden sich jetzt Marker, die entfernt werden müssen. Der Inhalt kann nach belieben angepasst werden. Am Besten sollte aber nur der Konflikt gelöst werden. https://www.atlassian.com/de/git/tutorials/using-branches/merge-conflicts[Weitere Infos]
. 	`Continue Rebase`

=== Rebase Conflict lösen

https://www.atlassian.com/de/git/tutorials/using-branches/merge-conflicts




== Other stuff
Projekt-Management Board in der Orga
Dokumentation mit KANBAN Board
Entwicklung mit Board (später)

Wollen Coaches auch Boards sehen?